# src/app/gui/resources/resources_rc.py

# This file is auto-generated by pyrcc6
# To regenerate, run: pyrcc6 resources.qrc -o resources_rc.py

# Placeholder content. Replace with actual compiled resources.
